### ISSUE TITLE
Comment

### ISSUE THREAD

**Issue by CreatorB** [SunDi3yansyah/mac-osx-lion-theme#1]
ngeri :+1: hahaha linux nya ndi? kok malah mac, owh ya ini bro yg kata ku kemaren https://www.youtube.com/watch?v=Md3TJ3zA_so di youtube banyak kok produk produk laen yang ikut indigo incubator.

**Comment by SunDi3yansyah** [comment]
hahahahaha belum sempat bro, klo perlu nanti sekalian remastering.... lg banyak project :dancer: 
komen di twitter/fb/linked aja bro seharusnya jangan di github, ini issues cuma untuk tracking project :+1:

**Comment by CreatorB** [comment]
mantab (y).......wakakaka ya bro, sorry emang sengaja :stuck_out_tongue: soale golek fb ne angel ckckck, wes ra usah di balessi menneh issue ki [CLOSED]
